TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
Preloading suits...
Preloading Toon heads...
Preloading avatars...
Traceback (most recent call last):
  File "D:\Documents\ToontownSourcecode\Toontown\toontown\toonbase\ClientStart.py", line 234, in loadScripts
    execfile('mods/'+scriptName,globals())
  File "mods/Compilation.txt", line 206, in <module>
    toonAnywhere = DirectButton(text = ("Enable Toonup anywhere", "ENABLE TOONUP ANYWHERE", "enable toonup anywhere", "enable toonup anywhere"), scale=.06, pos = (-1,-0,-.3), command=ToonupAnywhere.toonUpSetUp)
NameError: name 'ToonupAnywhere' is not defined

phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['FndsLst_ScrollUp', 'FndsLst_ScrollDN', 'FndsLst_ScrollUp_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['FndsLst_ScrollUp', 'FndsLst_ScrollDN', 'FndsLst_ScrollUp_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3/models/gui/quit_button.bam
['QuitBtn_UP', 'QuitBtn_DN', 'QuitBtn_RLVR']
phase_3/models/gui/quit_button.bam
['QuitBtn_UP', 'QuitBtn_DN', 'QuitBtn_RLVR']
phase_3/models/gui/quit_button.bam
['QuitBtn_UP', 'QuitBtn_DN', 'QuitBtn_RLVR']
phase_3/models/gui/quit_button.bam
['QuitBtn_UP', 'QuitBtn_DN', 'QuitBtn_RLVR']
test2
{402000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x1BD53328>, 401000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x1BD56300>, 404000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x1C03E3C8>, 405000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x1C03E328>, 403000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x1C038BE8>}
__handleAvatarChooserDone: 100000013, 'Little Zippy', ('rsl', 'ls', 'l', 'm', 19, 0, 19, 19, 10, 9, 0, 9, 7, 0), 1
2
Reading DNA file... phase_4/dna/storage.pdna
Reading DNA file... phase_3.5/dna/storage_interior.pdna
Reading DNA file... phase_6/dna/storage_DD.pdna
Reading DNA file... phase_6/dna/storage_DD_sz.pdna
Reading DNA file... phase_6/dna/donalds_dock_sz.pdna
Reading DNA file... phase_5/dna/storage_town.pdna
Reading DNA file... phase_6/dna/storage_DD_town.pdna
Reading DNA file... phase_6/dna/donalds_dock_1100.pdna
Exception occurred while processing Func-loadGagshop-340 of Sequence-195:
Sequence-195:
  0.000 Sequence-195 {
  0.000   *Func-loadGagshop-340
  0.000   Wait dur 1
  1.000   *Func-buyGags-341
  1.000   Wait dur 0.5
  1.500   *Func-unloadGagshop-342
  1.500 }

Traceback (most recent call last):
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\showbase\ShowBase.py", line 1801, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\interval\IntervalManager.py", line 96, in step
    self.__doPythonCallbacks()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\interval\IntervalManager.py", line 124, in __doPythonCallbacks
    self.ivals[index].privPostEvent()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\interval\MetaInterval.py", line 518, in privPostEvent
    self.__doPythonCallbacks()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\interval\MetaInterval.py", line 494, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\interval\Interval.py", line 207, in privDoEvent
    self.privInstant()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
  File "Gag Trainer Toontask.txt", line 721, in loadGagshop
    self.contextId = base.cr.addInterest(base.localAvatar.defaultShard, self.gagshop_zoneId, 4, event=None)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\distributed\DoInterestManager.py", line 190, in addInterest
    self._sendAddInterest(handle, contextId, parentId, zoneIdList, description)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\distributed\DoInterestManager.py", line 501, in _sendAddInterest
    action, description, handle, contextId, parentId, zoneIdList)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\distributed\DoInterestManager.py", line 446, in _addDebugInterestHistory
    DoInterestManager._debug_maxDescriptionLen, len(description))
TypeError: object of type 'int' has no len()
Traceback (most recent call last):
  File "otp\otpbase\OTPBase.py", line 236, in run
    taskMgr.run()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\task\Task.py", line 502, in run
    self.step()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\task\Task.py", line 460, in step
    self.mgr.poll()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\showbase\ShowBase.py", line 1801, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\interval\IntervalManager.py", line 96, in step
    self.__doPythonCallbacks()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\interval\IntervalManager.py", line 124, in __doPythonCallbacks
    self.ivals[index].privPostEvent()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\interval\MetaInterval.py", line 518, in privPostEvent
    self.__doPythonCallbacks()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\interval\MetaInterval.py", line 494, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\interval\Interval.py", line 207, in privDoEvent
    self.privInstant()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
  File "Gag Trainer Toontask.txt", line 721, in loadGagshop
    self.contextId = base.cr.addInterest(base.localAvatar.defaultShard, self.gagshop_zoneId, 4, event=None)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\distributed\DoInterestManager.py", line 190, in addInterest
    self._sendAddInterest(handle, contextId, parentId, zoneIdList, description)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\distributed\DoInterestManager.py", line 501, in _sendAddInterest
    action, description, handle, contextId, parentId, zoneIdList)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\distributed\DoInterestManager.py", line 446, in _addDebugInterestHistory
    DoInterestManager._debug_maxDescriptionLen, len(description))
TypeError: object of type 'int' has no len()
